[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
node_staking = "Z9ZruYv5kKRZJBej1at4FNv1CWDbonvfZnaKd639cwk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/node_staking_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
