[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
node_staking = "6TMoqcXXGgtyEtzhz9KR1YpBNGw9Zj9MEi9vnASLzAvh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/yb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

